[phases.setup]
nixPkgs = ["nodejs_20", "chromium", "nss", "freetype", "harfbuzz", "ca-certificates", "fontconfig"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[start]
cmd = "node index.js"
